<?php

// autoload.php @generated by Composer

require_once '/home/parson_chen/test/doctrine2-tutorial/vendor/' . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInit69c428dcc9931dcda141fbc46cfd10e5::getLoader();
